package blackmediamanager.database.domain;
// Generated 23.05.2016 22:31:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Audiolinepos generated by hbm2java
 */
public class Audiolinepos  implements java.io.Serializable {


     private Integer id;
     private String audioLanguage;
     private Integer audioBitrate;
     private String audioFormat;
     private String audioChannels;
     private Boolean dtsMod;
     private Set audiolines = new HashSet(0);

    public Audiolinepos() {
    }

    public Audiolinepos(String audioLanguage, Integer audioBitrate, String audioFormat, String audioChannels, Boolean dtsMod, Set audiolines) {
       this.audioLanguage = audioLanguage;
       this.audioBitrate = audioBitrate;
       this.audioFormat = audioFormat;
       this.audioChannels = audioChannels;
       this.dtsMod = dtsMod;
       this.audiolines = audiolines;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAudioLanguage() {
        return this.audioLanguage;
    }
    
    public void setAudioLanguage(String audioLanguage) {
        this.audioLanguage = audioLanguage;
    }
    public Integer getAudioBitrate() {
        return this.audioBitrate;
    }
    
    public void setAudioBitrate(Integer audioBitrate) {
        this.audioBitrate = audioBitrate;
    }
    public String getAudioFormat() {
        return this.audioFormat;
    }
    
    public void setAudioFormat(String audioFormat) {
        this.audioFormat = audioFormat;
    }
    public String getAudioChannels() {
        return this.audioChannels;
    }
    
    public void setAudioChannels(String audioChannels) {
        this.audioChannels = audioChannels;
    }
    public Boolean getDtsMod() {
        return this.dtsMod;
    }
    
    public void setDtsMod(Boolean dtsMod) {
        this.dtsMod = dtsMod;
    }
    public Set getAudiolines() {
        return this.audiolines;
    }
    
    public void setAudiolines(Set audiolines) {
        this.audiolines = audiolines;
    }




}


