package blackmediamanager.database.domain;
// Generated 23.05.2016 22:31:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Genrepos generated by hbm2java
 */
public class Genrepos  implements java.io.Serializable {


     private Integer id;
     private String type;
     private Set genres = new HashSet(0);

    public Genrepos() {
    }

    public Genrepos(String type, Set genres) {
       this.type = type;
       this.genres = genres;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getGenres() {
        return this.genres;
    }
    
    public void setGenres(Set genres) {
        this.genres = genres;
    }




}


