package blackmediamanager.database.domain;
// Generated 03.06.2016 20:33:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Movie generated by hbm2java
 */
public class Movie  implements java.io.Serializable {


     private Integer id;
     private MovieCollection movieCollection;
     private Tmdbinfo tmdbinfo;
     private Videoline videoline;
     private Byte active;
     private String note;
     private Boolean remux;
     private String fileName;
     private Double fileSize;
     private String fileFormat;
     private Date dateAdded;
     private Date dateModified;
     private Set movieHasEditions = new HashSet(0);
     private Set movieHasGenres = new HashSet(0);
     private Set movieHasOwners = new HashSet(0);
     private Set movieHasAudiolines = new HashSet(0);

    public Movie() {
    }

    public Movie(MovieCollection movieCollection, Tmdbinfo tmdbinfo, Videoline videoline, Byte active, String note, Boolean remux, String fileName, Double fileSize, String fileFormat, Date dateAdded, Date dateModified, Set movieHasEditions, Set movieHasGenres, Set movieHasOwners, Set movieHasAudiolines) {
       this.movieCollection = movieCollection;
       this.tmdbinfo = tmdbinfo;
       this.videoline = videoline;
       this.active = active;
       this.note = note;
       this.remux = remux;
       this.fileName = fileName;
       this.fileSize = fileSize;
       this.fileFormat = fileFormat;
       this.dateAdded = dateAdded;
       this.dateModified = dateModified;
       this.movieHasEditions = movieHasEditions;
       this.movieHasGenres = movieHasGenres;
       this.movieHasOwners = movieHasOwners;
       this.movieHasAudiolines = movieHasAudiolines;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MovieCollection getMovieCollection() {
        return this.movieCollection;
    }
    
    public void setMovieCollection(MovieCollection movieCollection) {
        this.movieCollection = movieCollection;
    }
    public Tmdbinfo getTmdbinfo() {
        return this.tmdbinfo;
    }
    
    public void setTmdbinfo(Tmdbinfo tmdbinfo) {
        this.tmdbinfo = tmdbinfo;
    }
    public Videoline getVideoline() {
        return this.videoline;
    }
    
    public void setVideoline(Videoline videoline) {
        this.videoline = videoline;
    }
    public Byte getActive() {
        return this.active;
    }
    
    public void setActive(Byte active) {
        this.active = active;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Boolean getRemux() {
        return this.remux;
    }
    
    public void setRemux(Boolean remux) {
        this.remux = remux;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public Double getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(Double fileSize) {
        this.fileSize = fileSize;
    }
    public String getFileFormat() {
        return this.fileFormat;
    }
    
    public void setFileFormat(String fileFormat) {
        this.fileFormat = fileFormat;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
    public Set getMovieHasEditions() {
        return this.movieHasEditions;
    }
    
    public void setMovieHasEditions(Set movieHasEditions) {
        this.movieHasEditions = movieHasEditions;
    }
    public Set getMovieHasGenres() {
        return this.movieHasGenres;
    }
    
    public void setMovieHasGenres(Set movieHasGenres) {
        this.movieHasGenres = movieHasGenres;
    }
    public Set getMovieHasOwners() {
        return this.movieHasOwners;
    }
    
    public void setMovieHasOwners(Set movieHasOwners) {
        this.movieHasOwners = movieHasOwners;
    }
    public Set getMovieHasAudiolines() {
        return this.movieHasAudiolines;
    }
    
    public void setMovieHasAudiolines(Set movieHasAudiolines) {
        this.movieHasAudiolines = movieHasAudiolines;
    }




}


