package blackmediamanager.database.domain;
// Generated 03.06.2016 20:33:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MovieCollection generated by hbm2java
 */
public class MovieCollection  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set movies = new HashSet(0);

    public MovieCollection() {
    }

    public MovieCollection(String name, Set movies) {
       this.name = name;
       this.movies = movies;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getMovies() {
        return this.movies;
    }
    
    public void setMovies(Set movies) {
        this.movies = movies;
    }




}


