package blackmediamanager.database.domain;
// Generated 03.06.2016 20:33:52 by Hibernate Tools 4.3.1



/**
 * MovieHasEdition generated by hbm2java
 */
public class MovieHasEdition  implements java.io.Serializable {


     private Integer id;
     private Edition edition;
     private Movie movie;

    public MovieHasEdition() {
    }

    public MovieHasEdition(Edition edition, Movie movie) {
       this.edition = edition;
       this.movie = movie;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Edition getEdition() {
        return this.edition;
    }
    
    public void setEdition(Edition edition) {
        this.edition = edition;
    }
    public Movie getMovie() {
        return this.movie;
    }
    
    public void setMovie(Movie movie) {
        this.movie = movie;
    }




}


