package blackmediamanager.database.domain;
// Generated 03.06.2016 20:33:52 by Hibernate Tools 4.3.1



/**
 * MovieHasAudioline generated by hbm2java
 */
public class MovieHasAudioline  implements java.io.Serializable {


     private Integer id;
     private Audioline audioline;
     private Movie movie;

    public MovieHasAudioline() {
    }

    public MovieHasAudioline(Audioline audioline, Movie movie) {
       this.audioline = audioline;
       this.movie = movie;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Audioline getAudioline() {
        return this.audioline;
    }
    
    public void setAudioline(Audioline audioline) {
        this.audioline = audioline;
    }
    public Movie getMovie() {
        return this.movie;
    }
    
    public void setMovie(Movie movie) {
        this.movie = movie;
    }




}


