package blackmediamanager.database.domain;
// Generated 03.06.2016 20:33:52 by Hibernate Tools 4.3.1



/**
 * MovieHasGenre generated by hbm2java
 */
public class MovieHasGenre  implements java.io.Serializable {


     private Integer id;
     private Genre genre;
     private Movie movie;

    public MovieHasGenre() {
    }

    public MovieHasGenre(Genre genre, Movie movie) {
       this.genre = genre;
       this.movie = movie;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Genre getGenre() {
        return this.genre;
    }
    
    public void setGenre(Genre genre) {
        this.genre = genre;
    }
    public Movie getMovie() {
        return this.movie;
    }
    
    public void setMovie(Movie movie) {
        this.movie = movie;
    }




}


