package blackmediamanager.database.domain;
// Generated 23.05.2016 22:31:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Movie generated by hbm2java
 */
public class Movie  implements java.io.Serializable {


     private int id;
     private Tmdbinfo tmdbinfo;
     private Videoline videoline;
     private Byte active;
     private String note;
     private Boolean remux;
     private String edition;
     private Integer duration;
     private String fileName;
     private Integer year;
     private Double fileSize;
     private String fileFormat;
     private Date dateAdded;
     private Date dateModified;
     private Set<Genre> genres = new HashSet(0);
     private Set<Audioline> audiolines = new HashSet(0);
     private Set<Owner> owners = new HashSet(0);

    public Movie() {
    }

	
    public Movie(int id, Date dateModified) {
        this.id = id;
        this.dateModified = dateModified;
    }
    public Movie(int id, Tmdbinfo tmdbinfo, Videoline videoline, Byte active, String note, Boolean remux, String edition, Integer duration, String fileName, Integer year, Double fileSize, String fileFormat, Date dateAdded, Date dateModified, Set genres, Set audiolines, Set owners) {
       this.id = id;
       this.tmdbinfo = tmdbinfo;
       this.videoline = videoline;
       this.active = active;
       this.note = note;
       this.remux = remux;
       this.edition = edition;
       this.duration = duration;
       this.fileName = fileName;
       this.year = year;
       this.fileSize = fileSize;
       this.fileFormat = fileFormat;
       this.dateAdded = dateAdded;
       this.dateModified = dateModified;
       this.genres = genres;
       this.audiolines = audiolines;
       this.owners = owners;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tmdbinfo getTmdbinfo() {
        return this.tmdbinfo;
    }
    
    public void setTmdbinfo(Tmdbinfo tmdbinfo) {
        this.tmdbinfo = tmdbinfo;
    }
    public Videoline getVideoline() {
        return this.videoline;
    }
    
    public void setVideoline(Videoline videoline) {
        this.videoline = videoline;
    }
    public Byte getActive() {
        return this.active;
    }
    
    public void setActive(Byte active) {
        this.active = active;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Boolean getRemux() {
        return this.remux;
    }
    
    public void setRemux(Boolean remux) {
        this.remux = remux;
    }
    public String getEdition() {
        return this.edition;
    }
    
    public void setEdition(String edition) {
        this.edition = edition;
    }
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Double getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(Double fileSize) {
        this.fileSize = fileSize;
    }
    public String getFileFormat() {
        return this.fileFormat;
    }
    
    public void setFileFormat(String fileFormat) {
        this.fileFormat = fileFormat;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
    public Set<Genre> getGenres() {
        return this.genres;
    }
    
    public void setGenres(Set genres) {
        this.genres = genres;
    }
    public Set<Audioline> getAudiolines() {
        return this.audiolines;
    }
    
    public void setAudiolines(Set audiolines) {
        this.audiolines = audiolines;
    }
    public Set<Owner> getOwners() {
        return this.owners;
    }
    
    public void setOwners(Set owners) {
        this.owners = owners;
    }




}


