package blackmediamanager.database.domain;
// Generated 03.06.2016 20:33:52 by Hibernate Tools 4.3.1



/**
 * MovieHasOwner generated by hbm2java
 */
public class MovieHasOwner  implements java.io.Serializable {


     private Integer id;
     private Movie movie;
     private Owner owner;
     private String hdd;

    public MovieHasOwner() {
    }

	
    public MovieHasOwner(Movie movie, Owner owner) {
        this.movie = movie;
        this.owner = owner;
    }
    public MovieHasOwner(Movie movie, Owner owner, String hdd) {
       this.movie = movie;
       this.owner = owner;
       this.hdd = hdd;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Movie getMovie() {
        return this.movie;
    }
    
    public void setMovie(Movie movie) {
        this.movie = movie;
    }
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }
    public String getHdd() {
        return this.hdd;
    }
    
    public void setHdd(String hdd) {
        this.hdd = hdd;
    }




}


