package blackmediamanager.database.domain;
// Generated 03.06.2016 19:51:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Owner generated by hbm2java
 */
public class Owner  implements java.io.Serializable {


     private Integer id;
     private String ownerName;
     private Set seasonHasOwners = new HashSet(0);
     private Set movieHasOwners = new HashSet(0);

    public Owner() {
    }

    public Owner(String ownerName, Set seasonHasOwners, Set movieHasOwners) {
       this.ownerName = ownerName;
       this.seasonHasOwners = seasonHasOwners;
       this.movieHasOwners = movieHasOwners;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getOwnerName() {
        return this.ownerName;
    }
    
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }
    public Set getSeasonHasOwners() {
        return this.seasonHasOwners;
    }
    
    public void setSeasonHasOwners(Set seasonHasOwners) {
        this.seasonHasOwners = seasonHasOwners;
    }
    public Set getMovieHasOwners() {
        return this.movieHasOwners;
    }
    
    public void setMovieHasOwners(Set movieHasOwners) {
        this.movieHasOwners = movieHasOwners;
    }




}


