package blackmediamanager.database.domain;
// Generated 03.06.2016 20:33:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Season generated by hbm2java
 */
public class Season  implements java.io.Serializable {


     private Integer id;
     private Videoline videoline;
     private Integer season;
     private Integer duration;
     private Double averageFileSize;
     private Date year;
     private String note;
     private Set seasonHasAudiolines = new HashSet(0);
     private Set seasonHasOwners = new HashSet(0);
     private Set tvshowHasSeasons = new HashSet(0);

    public Season() {
    }

	
    public Season(Videoline videoline) {
        this.videoline = videoline;
    }
    public Season(Videoline videoline, Integer season, Integer duration, Double averageFileSize, Date year, String note, Set seasonHasAudiolines, Set seasonHasOwners, Set tvshowHasSeasons) {
       this.videoline = videoline;
       this.season = season;
       this.duration = duration;
       this.averageFileSize = averageFileSize;
       this.year = year;
       this.note = note;
       this.seasonHasAudiolines = seasonHasAudiolines;
       this.seasonHasOwners = seasonHasOwners;
       this.tvshowHasSeasons = tvshowHasSeasons;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Videoline getVideoline() {
        return this.videoline;
    }
    
    public void setVideoline(Videoline videoline) {
        this.videoline = videoline;
    }
    public Integer getSeason() {
        return this.season;
    }
    
    public void setSeason(Integer season) {
        this.season = season;
    }
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }
    public Double getAverageFileSize() {
        return this.averageFileSize;
    }
    
    public void setAverageFileSize(Double averageFileSize) {
        this.averageFileSize = averageFileSize;
    }
    public Date getYear() {
        return this.year;
    }
    
    public void setYear(Date year) {
        this.year = year;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Set getSeasonHasAudiolines() {
        return this.seasonHasAudiolines;
    }
    
    public void setSeasonHasAudiolines(Set seasonHasAudiolines) {
        this.seasonHasAudiolines = seasonHasAudiolines;
    }
    public Set getSeasonHasOwners() {
        return this.seasonHasOwners;
    }
    
    public void setSeasonHasOwners(Set seasonHasOwners) {
        this.seasonHasOwners = seasonHasOwners;
    }
    public Set getTvshowHasSeasons() {
        return this.tvshowHasSeasons;
    }
    
    public void setTvshowHasSeasons(Set tvshowHasSeasons) {
        this.tvshowHasSeasons = tvshowHasSeasons;
    }




}


