package blackmediamanager.database.domain;
// Generated 03.06.2016 20:33:52 by Hibernate Tools 4.3.1



/**
 * SeasonHasAudioline generated by hbm2java
 */
public class SeasonHasAudioline  implements java.io.Serializable {


     private Integer id;
     private Audioline audioline;
     private Season season;

    public SeasonHasAudioline() {
    }

    public SeasonHasAudioline(Audioline audioline, Season season) {
       this.audioline = audioline;
       this.season = season;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Audioline getAudioline() {
        return this.audioline;
    }
    
    public void setAudioline(Audioline audioline) {
        this.audioline = audioline;
    }
    public Season getSeason() {
        return this.season;
    }
    
    public void setSeason(Season season) {
        this.season = season;
    }




}


