package blackmediamanager.database.domain;
// Generated 03.06.2016 20:33:52 by Hibernate Tools 4.3.1



/**
 * SeasonHasOwner generated by hbm2java
 */
public class SeasonHasOwner  implements java.io.Serializable {


     private Integer id;
     private Owner owner;
     private Season season;

    public SeasonHasOwner() {
    }

    public SeasonHasOwner(Owner owner, Season season) {
       this.owner = owner;
       this.season = season;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }
    public Season getSeason() {
        return this.season;
    }
    
    public void setSeason(Season season) {
        this.season = season;
    }




}


