package blackmediamanager.database.domain;
// Generated 03.06.2016 20:33:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tmdbinfo generated by hbm2java
 */
public class Tmdbinfo  implements java.io.Serializable {


     private Integer tmdbId;
     private String title;
     private String orginalTitel;
     private Date releaseDate;
     private Double rating;
     private Integer duration;
     private String overview;
     private String tagline;
     private String coverUrl;
     private Set movies = new HashSet(0);

    public Tmdbinfo() {
    }

    public Tmdbinfo(String title, String orginalTitel, Date releaseDate, Double rating, Integer duration, String overview, String tagline, String coverUrl, Set movies) {
       this.title = title;
       this.orginalTitel = orginalTitel;
       this.releaseDate = releaseDate;
       this.rating = rating;
       this.duration = duration;
       this.overview = overview;
       this.tagline = tagline;
       this.coverUrl = coverUrl;
       this.movies = movies;
    }
   
    public Integer getTmdbId() {
        return this.tmdbId;
    }
    
    public void setTmdbId(Integer tmdbId) {
        this.tmdbId = tmdbId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getOrginalTitel() {
        return this.orginalTitel;
    }
    
    public void setOrginalTitel(String orginalTitel) {
        this.orginalTitel = orginalTitel;
    }
    public Date getReleaseDate() {
        return this.releaseDate;
    }
    
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }
    public Double getRating() {
        return this.rating;
    }
    
    public void setRating(Double rating) {
        this.rating = rating;
    }
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }
    public String getOverview() {
        return this.overview;
    }
    
    public void setOverview(String overview) {
        this.overview = overview;
    }
    public String getTagline() {
        return this.tagline;
    }
    
    public void setTagline(String tagline) {
        this.tagline = tagline;
    }
    public String getCoverUrl() {
        return this.coverUrl;
    }
    
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }
    public Set getMovies() {
        return this.movies;
    }
    
    public void setMovies(Set movies) {
        this.movies = movies;
    }




}


