package blackmediamanager.database.domain;
// Generated 03.06.2016 20:33:52 by Hibernate Tools 4.3.1



/**
 * TvshowHasGenre generated by hbm2java
 */
public class TvshowHasGenre  implements java.io.Serializable {


     private Integer id;
     private Genre genre;
     private Tvshow tvshow;

    public TvshowHasGenre() {
    }

    public TvshowHasGenre(Genre genre, Tvshow tvshow) {
       this.genre = genre;
       this.tvshow = tvshow;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Genre getGenre() {
        return this.genre;
    }
    
    public void setGenre(Genre genre) {
        this.genre = genre;
    }
    public Tvshow getTvshow() {
        return this.tvshow;
    }
    
    public void setTvshow(Tvshow tvshow) {
        this.tvshow = tvshow;
    }




}


