package blackmediamanager.database.domain;
// Generated 03.06.2016 20:33:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tvshow generated by hbm2java
 */
public class Tvshow  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Byte active;
     private Date dateAdded;
     private Date dateModified;
     private Set tvshowHasGenres = new HashSet(0);
     private Set tvshowHasSeasons = new HashSet(0);

    public Tvshow() {
    }

    public Tvshow(String name, Byte active, Date dateAdded, Date dateModified, Set tvshowHasGenres, Set tvshowHasSeasons) {
       this.name = name;
       this.active = active;
       this.dateAdded = dateAdded;
       this.dateModified = dateModified;
       this.tvshowHasGenres = tvshowHasGenres;
       this.tvshowHasSeasons = tvshowHasSeasons;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Byte getActive() {
        return this.active;
    }
    
    public void setActive(Byte active) {
        this.active = active;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
    public Set getTvshowHasGenres() {
        return this.tvshowHasGenres;
    }
    
    public void setTvshowHasGenres(Set tvshowHasGenres) {
        this.tvshowHasGenres = tvshowHasGenres;
    }
    public Set getTvshowHasSeasons() {
        return this.tvshowHasSeasons;
    }
    
    public void setTvshowHasSeasons(Set tvshowHasSeasons) {
        this.tvshowHasSeasons = tvshowHasSeasons;
    }




}


