package database.domain;
// Generated 23.05.2016 22:31:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tmdbinfo generated by hbm2java
 */
public class Tmdbinfo  implements java.io.Serializable {


     private Integer id;
     private Integer tmdbId;
     private String title;
     private Date releasedDate;
     private Double rating;
     private String overview;
     private String tagline;
     private String coverUrl;
     private Set movies = new HashSet(0);

    public Tmdbinfo() {
    }

    public Tmdbinfo(Integer tmdbId, String title, Date releasedDate, Double rating, String overview, String tagline, String coverUrl, Set movies) {
       this.tmdbId = tmdbId;
       this.title = title;
       this.releasedDate = releasedDate;
       this.rating = rating;
       this.overview = overview;
       this.tagline = tagline;
       this.coverUrl = coverUrl;
       this.movies = movies;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getTmdbId() {
        return this.tmdbId;
    }
    
    public void setTmdbId(Integer tmdbId) {
        this.tmdbId = tmdbId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getReleasedDate() {
        return this.releasedDate;
    }
    
    public void setReleasedDate(Date releasedDate) {
        this.releasedDate = releasedDate;
    }
    public Double getRating() {
        return this.rating;
    }
    
    public void setRating(Double rating) {
        this.rating = rating;
    }
    public String getOverview() {
        return this.overview;
    }
    
    public void setOverview(String overview) {
        this.overview = overview;
    }
    public String getTagline() {
        return this.tagline;
    }
    
    public void setTagline(String tagline) {
        this.tagline = tagline;
    }
    public String getCoverUrl() {
        return this.coverUrl;
    }
    
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }
    public Set getMovies() {
        return this.movies;
    }
    
    public void setMovies(Set movies) {
        this.movies = movies;
    }




}


