package database.domain;
// Generated 23.05.2016 22:31:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Videoline generated by hbm2java
 */
public class Videoline  implements java.io.Serializable {


     private Integer id;
     private Integer videoBitrate;
     private String videoBitrateMode;
     private String aspectRatio;
     private Integer resolutionWidth;
     private Integer resolutionHeight;
     private Double framerate;
     private Set movies = new HashSet(0);

    public Videoline() {
    }

    public Videoline(Integer videoBitrate, String videoBitrateMode, String aspectRatio, Integer resolutionWidth, Integer resolutionHeight, Double framerate, Set movies) {
       this.videoBitrate = videoBitrate;
       this.videoBitrateMode = videoBitrateMode;
       this.aspectRatio = aspectRatio;
       this.resolutionWidth = resolutionWidth;
       this.resolutionHeight = resolutionHeight;
       this.framerate = framerate;
       this.movies = movies;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getVideoBitrate() {
        return this.videoBitrate;
    }
    
    public void setVideoBitrate(Integer videoBitrate) {
        this.videoBitrate = videoBitrate;
    }
    public String getVideoBitrateMode() {
        return this.videoBitrateMode;
    }
    
    public void setVideoBitrateMode(String videoBitrateMode) {
        this.videoBitrateMode = videoBitrateMode;
    }
    public String getAspectRatio() {
        return this.aspectRatio;
    }
    
    public void setAspectRatio(String aspectRatio) {
        this.aspectRatio = aspectRatio;
    }
    public Integer getResolutionWidth() {
        return this.resolutionWidth;
    }
    
    public void setResolutionWidth(Integer resolutionWidth) {
        this.resolutionWidth = resolutionWidth;
    }
    public Integer getResolutionHeight() {
        return this.resolutionHeight;
    }
    
    public void setResolutionHeight(Integer resolutionHeight) {
        this.resolutionHeight = resolutionHeight;
    }
    public Double getFramerate() {
        return this.framerate;
    }
    
    public void setFramerate(Double framerate) {
        this.framerate = framerate;
    }
    public Set getMovies() {
        return this.movies;
    }
    
    public void setMovies(Set movies) {
        this.movies = movies;
    }




}


