language: java
script: 
  - "mvn -f pom.xml clean verify"
  - "mvn -f pom.xml clean test"
  - "mvn -f pom.xml clean install"
  - "mvn -f pom.xml clean compile assembly:single"
jdk:
  - oraclejdk8
