package database.domain;
// Generated 30.04.2016 21:37:04 by Hibernate Tools 4.3.1



/**
 * Genre generated by hbm2java
 */
public class Genre  implements java.io.Serializable {


     private Integer id;
     private Genrepos genrepos;
     private Movie movie;

    public Genre() {
    }

    public Genre(Genrepos genrepos, Movie movie) {
       this.genrepos = genrepos;
       this.movie = movie;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Genrepos getGenrepos() {
        return this.genrepos;
    }
    
    public void setGenrepos(Genrepos genrepos) {
        this.genrepos = genrepos;
    }
    public Movie getMovie() {
        return this.movie;
    }
    
    public void setMovie(Movie movie) {
        this.movie = movie;
    }




}


