package database.domain;
// Generated 30.04.2016 21:37:04 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;


/**
 * Movie generated by hbm2java
 */


public class Movie  implements java.io.Serializable {


     private int id;
     private Tmdbinfo tmdbinfo;
     private Videoline videoline;
     private byte active;
     private String note;
     private boolean remux;
     private String edition;
     private int duration;
     private String fileName;
     private double fileSize;
     private String fileFormat;
     private Date date;
     private Set owners = new HashSet(0);
     private Set genres = new HashSet(0);
     private Set audiolines = new HashSet(0);

    public Movie() {
    }

	
    public Movie(int id, Tmdbinfo tmdbinfo, Videoline videoline, byte active, String note, boolean remux, String edition, int duration, String fileName, double fileSize, String fileFormat, Date date) {
        this.id = id;
        this.tmdbinfo = tmdbinfo;
        this.videoline = videoline;
        this.active = active;
        this.note = note;
        this.remux = remux;
        this.edition = edition;
        this.duration = duration;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.fileFormat = fileFormat;
        this.date = date;
    }
    public Movie(int id, Tmdbinfo tmdbinfo, Videoline videoline, byte active, String note, boolean remux, String edition, int duration, String fileName, double fileSize, String fileFormat, Date date, Set owners, Set genres, Set audiolines) {
       this.id = id;
       this.tmdbinfo = tmdbinfo;
       this.videoline = videoline;
       this.active = active;
       this.note = note;
       this.remux = remux;
       this.edition = edition;
       this.duration = duration;
       this.fileName = fileName;
       this.fileSize = fileSize;
       this.fileFormat = fileFormat;
       this.date = date;
       this.owners = owners;
       this.genres = genres;
       this.audiolines = audiolines;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Cascade({CascadeType.ALL})
    @ManyToOne(fetch = FetchType.LAZY)
    public Tmdbinfo getTmdbinfo() {
        return this.tmdbinfo;
    }
    
    public void setTmdbinfo(Tmdbinfo tmdbinfo) {
        this.tmdbinfo = tmdbinfo;
    }
    
    @Cascade({CascadeType.ALL})
    @ManyToOne(fetch = FetchType.LAZY)
    public Videoline getVideoline() {
        return this.videoline;
    }
    
    public void setVideoline(Videoline videoline) {
        this.videoline = videoline;
    }
    public byte getActive() {
        return this.active;
    }
    
    public void setActive(byte active) {
        this.active = active;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public boolean isRemux() {
        return this.remux;
    }
    
    public void setRemux(boolean remux) {
        this.remux = remux;
    }
    public String getEdition() {
        return this.edition;
    }
    
    public void setEdition(String edition) {
        this.edition = edition;
    }
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public double getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(double fileSize) {
        this.fileSize = fileSize;
    }
    public String getFileFormat() {
        return this.fileFormat;
    }
    
    public void setFileFormat(String fileFormat) {
        this.fileFormat = fileFormat;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Cascade({CascadeType.ALL})
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "Movie")
    public Set getOwners() {
        return this.owners;
    }
    
    public void setOwners(Set owners) {
        this.owners = owners;
    }
    
    @Cascade({CascadeType.ALL})
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "Movie")
    public Set getGenres() {
        return this.genres;
    }
    
    public void setGenres(Set genres) {
        this.genres = genres;
    }
    
    @Cascade({CascadeType.ALL})
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "Movie")
    public Set getAudiolines() {
        return this.audiolines;
    }
    
    public void setAudiolines(Set audiolines) {
        this.audiolines = audiolines;
    }




}


