package database.domain;
// Generated 29.04.2016 17:03:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Movie generated by hbm2java
 */
public class Movie  implements java.io.Serializable {


     private int id;
     private Tmdbinfo tmdbinfo;
     private Videoline videoline;
     private byte active;
     private String note;
     private boolean remux;
     private String edition;
     private Set owners = new HashSet(0);
     private Set genres = new HashSet(0);
     private Set audiolines = new HashSet(0);

    public Movie() {
    }

	
    public Movie(int id, Tmdbinfo tmdbinfo, Videoline videoline, byte active, String note, boolean remux, String edition) {
        this.id = id;
        this.tmdbinfo = tmdbinfo;
        this.videoline = videoline;
        this.active = active;
        this.note = note;
        this.remux = remux;
        this.edition = edition;
    }
    public Movie(int id, Tmdbinfo tmdbinfo, Videoline videoline, byte active, String note, boolean remux, String edition, Set owners, Set genres, Set audiolines) {
       this.id = id;
       this.tmdbinfo = tmdbinfo;
       this.videoline = videoline;
       this.active = active;
       this.note = note;
       this.remux = remux;
       this.edition = edition;
       this.owners = owners;
       this.genres = genres;
       this.audiolines = audiolines;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tmdbinfo getTmdbinfo() {
        return this.tmdbinfo;
    }
    
    public void setTmdbinfo(Tmdbinfo tmdbinfo) {
        this.tmdbinfo = tmdbinfo;
    }
    public Videoline getVideoline() {
        return this.videoline;
    }
    
    public void setVideoline(Videoline videoline) {
        this.videoline = videoline;
    }
    public byte getActive() {
        return this.active;
    }
    
    public void setActive(byte active) {
        this.active = active;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public boolean isRemux() {
        return this.remux;
    }
    
    public void setRemux(boolean remux) {
        this.remux = remux;
    }
    public String getEdition() {
        return this.edition;
    }
    
    public void setEdition(String edition) {
        this.edition = edition;
    }
    public Set getOwners() {
        return this.owners;
    }
    
    public void setOwners(Set owners) {
        this.owners = owners;
    }
    public Set getGenres() {
        return this.genres;
    }
    
    public void setGenres(Set genres) {
        this.genres = genres;
    }
    public Set getAudiolines() {
        return this.audiolines;
    }
    
    public void setAudiolines(Set audiolines) {
        this.audiolines = audiolines;
    }




}


