package database.domain;
// Generated 30.04.2016 21:37:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ownerpos generated by hbm2java
 */
public class Ownerpos  implements java.io.Serializable {


     private Integer id;
     private String ownerName;
     private Set owners = new HashSet(0);

    public Ownerpos() {
    }

	
    public Ownerpos(String ownerName) {
        this.ownerName = ownerName;
    }
    public Ownerpos(String ownerName, Set owners) {
       this.ownerName = ownerName;
       this.owners = owners;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getOwnerName() {
        return this.ownerName;
    }
    
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }
    public Set getOwners() {
        return this.owners;
    }
    
    public void setOwners(Set owners) {
        this.owners = owners;
    }




}


