package database.domain;
// Generated 29.04.2016 17:03:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tmdbinfo generated by hbm2java
 */
public class Tmdbinfo  implements java.io.Serializable {


     private Integer id;
     private int tmdbId;
     private String title;
     private int releasedYear;
     private double rating;
     private String overview;
     private String tagline;
     private String coverUrl;
     private Set movies = new HashSet(0);

    public Tmdbinfo() {
    }

	
    public Tmdbinfo(int tmdbId, String title, int releasedYear, double rating, String overview, String tagline, String coverUrl) {
        this.tmdbId = tmdbId;
        this.title = title;
        this.releasedYear = releasedYear;
        this.rating = rating;
        this.overview = overview;
        this.tagline = tagline;
        this.coverUrl = coverUrl;
    }
    public Tmdbinfo(int tmdbId, String title, int releasedYear, double rating, String overview, String tagline, String coverUrl, Set movies) {
       this.tmdbId = tmdbId;
       this.title = title;
       this.releasedYear = releasedYear;
       this.rating = rating;
       this.overview = overview;
       this.tagline = tagline;
       this.coverUrl = coverUrl;
       this.movies = movies;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getTmdbId() {
        return this.tmdbId;
    }
    
    public void setTmdbId(int tmdbId) {
        this.tmdbId = tmdbId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public int getReleasedYear() {
        return this.releasedYear;
    }
    
    public void setReleasedYear(int releasedYear) {
        this.releasedYear = releasedYear;
    }
    public double getRating() {
        return this.rating;
    }
    
    public void setRating(double rating) {
        this.rating = rating;
    }
    public String getOverview() {
        return this.overview;
    }
    
    public void setOverview(String overview) {
        this.overview = overview;
    }
    public String getTagline() {
        return this.tagline;
    }
    
    public void setTagline(String tagline) {
        this.tagline = tagline;
    }
    public String getCoverUrl() {
        return this.coverUrl;
    }
    
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }
    public Set getMovies() {
        return this.movies;
    }
    
    public void setMovies(Set movies) {
        this.movies = movies;
    }




}


