package database.domain;
// Generated 30.04.2016 21:37:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Videoline generated by hbm2java
 */
public class Videoline  implements java.io.Serializable {


     private Integer id;
     private int videoBitrate;
     private String videoBitrateMode;
     private String aspectRatio;
     private int resolutionWidth;
     private int resolutionHeight;
     private double framerate;
     private Set movies = new HashSet(0);

    public Videoline() {
    }

	
    public Videoline(int videoBitrate, String videoBitrateMode, String aspectRatio, int resolutionWidth, int resolutionHeight, double framerate) {
        this.videoBitrate = videoBitrate;
        this.videoBitrateMode = videoBitrateMode;
        this.aspectRatio = aspectRatio;
        this.resolutionWidth = resolutionWidth;
        this.resolutionHeight = resolutionHeight;
        this.framerate = framerate;
    }
    public Videoline(int videoBitrate, String videoBitrateMode, String aspectRatio, int resolutionWidth, int resolutionHeight, double framerate, Set movies) {
       this.videoBitrate = videoBitrate;
       this.videoBitrateMode = videoBitrateMode;
       this.aspectRatio = aspectRatio;
       this.resolutionWidth = resolutionWidth;
       this.resolutionHeight = resolutionHeight;
       this.framerate = framerate;
       this.movies = movies;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getVideoBitrate() {
        return this.videoBitrate;
    }
    
    public void setVideoBitrate(int videoBitrate) {
        this.videoBitrate = videoBitrate;
    }
    public String getVideoBitrateMode() {
        return this.videoBitrateMode;
    }
    
    public void setVideoBitrateMode(String videoBitrateMode) {
        this.videoBitrateMode = videoBitrateMode;
    }
    public String getAspectRatio() {
        return this.aspectRatio;
    }
    
    public void setAspectRatio(String aspectRatio) {
        this.aspectRatio = aspectRatio;
    }
    public int getResolutionWidth() {
        return this.resolutionWidth;
    }
    
    public void setResolutionWidth(int resolutionWidth) {
        this.resolutionWidth = resolutionWidth;
    }
    public int getResolutionHeight() {
        return this.resolutionHeight;
    }
    
    public void setResolutionHeight(int resolutionHeight) {
        this.resolutionHeight = resolutionHeight;
    }
    public double getFramerate() {
        return this.framerate;
    }
    
    public void setFramerate(double framerate) {
        this.framerate = framerate;
    }
    public Set getMovies() {
        return this.movies;
    }
    
    public void setMovies(Set movies) {
        this.movies = movies;
    }




}


